In [1]:
import numpy as numpy

# --- searching --- #
l = [1, 4, 9, 16, 25, 36, 49, 64, 81, 36]
n = numpy.array(l)
print(n)

# --- 1D array --- #
print("1D array")
x = numpy.where(n == 36) # --> returns a tuple of arrays with index and type
print(x[0])
print(n[x[0]])
print(numpy.searchsorted(n, 36))  # --> returns index in sorted array

y = numpy.where(n%2 == 0) # --> returns a tuple of arrays with index and type
print(y) # --> returns a tuple of arrays with index and type
print(n[y[0]]) # --> returns a tuple of arrays with index and type


[ 1  4  9 16 25 36 49 64 81 36]
1D array
[5 9]
[36 36]
5
(array([1, 3, 5, 7, 9], dtype=int64),)
[ 4 16 36 64 36]
