In [1]:
import numpy as numpy

l = [1, 4, 9, 16, 25, 36, 49, 64, 81]
l2 = [-1, -4, -9, -16, -25, -36, -49, 64, 81]
n = numpy.array(l)
n2 = numpy.array(l2)

print(n)

# Square root of each element #
print(numpy.sqrt(n))

# Absolute value of each element #
print(numpy.absolute(n2))  # --> returns positive value

# Exponential of each element #
print(numpy.exp(n))  # --> e^x

# Logarithm of each element #
print(numpy.log(n))  # --> ln(x)

# Min/Max of each element #
print(numpy.min(n))
print(numpy.max(n))

# Sign of each element #
print(numpy.sign(n2)) # --> returns -1 if negative, 0 if 0, 1 if positive

[ 1  4  9 16 25 36 49 64 81]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1  4  9 16 25 36 49 64 81]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15 1.90734657e+21 6.23514908e+27
 1.50609731e+35]
[0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894
 3.8918203  4.15888308 4.39444915]
1
81
[-1 -1 -1 -1 -1 -1 -1  1  1]
