In [2]:
import numpy as numpy

# --- slicing --- #
li = [1, 2, 3, 4, 5, 6, 7, 8, 9]
n = numpy.array(li)

print(n[1:4])  # --> 2, 3, 4
print(n[:4])  # --> 1, 2, 3, 4 (start from 0)
print(n[4:])  # --> 5, 6, 7, 8, 9 (end at last index)
print(n[0:9:2])  # --> 2, 4, 6, 8 (start:end:step)
print(n[-9:])  # --> 1, 2, 3, 4, 5, 6, 7, 8, 9 (start from -9 to end)

# --- 2D array --- #
n1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(n1)
print(n1[2,2])  # --> 1, 2, 4, 5 (row,col)

[2 3 4]
[1 2 3 4]
[5 6 7 8 9]
[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
