In [24]:
import numpy as np
# Numpy --> Numeric Python
# ndarray --> n dimensional array
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1.shape) # length of array
l = ["SAMI","RIZWAN","THAKUR"] # python list to numpy array #
npl = np.array(l)
print(npl)
print(npl[2])
# print(l[1])
# --- arrange func --- #
np2 = np.arange(9) # make list from 0 --> l-1
print(np2)
np3 = np.arange(1,14) # make list from s --> l-1
print(np3) 


[0 1 2 3 4 5 6 7 8 9]
(10,)
['SAMI' 'RIZWAN' 'THAKUR']
THAKUR
[0 1 2 3 4 5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


In [17]:
# --- zero func --- #
np4 = np.zeros(10) # make a list of 0 of size n
print(np4)
# multi-dimensional #
np5 = np.zeros((3,5)) # --> creates 3D array with 5 zero in each dim
print(np5)
# --- full func --- #
np6 = np.full((10),3)
print(np6)
np7 = np.full((3,5),9)
print(np7)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[3 3 3 3 3 3 3 3 3 3]
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
