In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd 
import seaborn as sns 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
url="https://drive.google.com/file/d/1VD06DjyGegNAWdJxFqKW-BtNsSbZsbez/view?usp=drive_link"
url='https://drive.google.com/uc?id=' + url.split('/')[-2]
ad = pd.read_csv(url)

In [3]:
X = ad.loc[: , 'TV':'newspaper']
y = ad['sales']

<h1><mark>MODEL TRAINING</mark></h1>

In [4]:
model = LinearRegression()
model.fit(X, y)
test_predictions = model.predict(X)

<h1><mark>REGRESSION EQUATION</mark></h1>

In [7]:
coefficients = model.coef_
# Get intercept
intercept = model.intercept_
# Print equation
print("Regression Equation:")
print("y = {:.4f} + {:.4f} * x1 + {:.4f} * x2^2 + {:.4f} * x3^3".format(intercept, coefficients[0], coefficients[1], coefficients[2]))

Regression Equation:
y = 2.9389 + 0.0458 * x1 + 0.1885 * x2^2 + -0.0010 * x3^3


<h2><mark>Serialize MODEL using JOBLIB</mark></h2>

In [8]:
from joblib import dump,load

In [9]:
dump(model , "final_sales_model.joblib")

['final_sales_model.joblib']

In [10]:
loaded = load('final_sales_model.joblib')

In [11]:
loaded.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [14]:
campaign = [[149 , 22 , 12]]

In [15]:
loaded.predict(campaign)

C:\Users\SAMI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([13.893032])

In [16]:
model.predict(campaign)

C:\Users\SAMI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([13.893032])